From python:3.4 

USER root
RUN pip install --upgrade pip
RUN pip install flask && pip install flask --upgrade
#RUN pip install plotly && pip install plotly --upgrade
#RUN pip install numpy && pip install numpy --upgrade
#RUN pip install pandas && pip install pandas --upgrade
RUN cd && mkdir apps
RUN apt-get update && apt-get install -y vim
